//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 02:39:47 DU CEST 
//


package com.aionemu.packetsamurai.utils.collector.data.npcskills;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NpcSkillList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NpcSkillList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="npcskill" type="{}NpcSkillTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="npcid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NpcSkillList", propOrder = {
    "npcskill"
})
public class NpcSkillList implements Comparable<NpcSkillList>{

    protected List<NpcSkillTemplate> npcskill;
    @XmlAttribute
    protected Integer npcid;

    /**
     * Gets the value of the npcskill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npcskill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNpcskill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NpcSkillTemplate }
     * 
     * 
     */
    public List<NpcSkillTemplate> getNpcskill() {
        if (npcskill == null) {
            npcskill = new ArrayList<NpcSkillTemplate>();
        }
        return this.npcskill;
    }

    /**
     * Gets the value of the npcid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNpcid() {
        return npcid;
    }

    /**
     * Sets the value of the npcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNpcid(Integer value) {
        this.npcid = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((npcid == null) ? 0 : npcid.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		NpcSkillList other = (NpcSkillList) obj;
		if (npcid == null) {
			if (other.npcid != null)
				return false;
		} else if (!npcid.equals(other.npcid))
			return false;
		return true;
	}

	@Override
	public int compareTo(NpcSkillList o) {
		return npcid-o.npcid;
	}

}
