//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.06 at 02:39:47 DU CEST 
//


package com.aionemu.packetsamurai.utils.collector.data.npcskills;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aionemu.packetsamurai.utils.collector.data.npcskills package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aionemu.packetsamurai.utils.collector.data.npcskills
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NpcSkillTemplates }
     * 
     */
    public NpcSkillTemplates createNpcSkillTemplates() {
        return new NpcSkillTemplates();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link NpcSkillTemplate }
     * 
     */
    public NpcSkillTemplate createNpcSkillTemplate() {
        return new NpcSkillTemplate();
    }

    /**
     * Create an instance of {@link NpcSkillList }
     * 
     */
    public NpcSkillList createNpcSkillList() {
        return new NpcSkillList();
    }

}
