//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 04:04:44 PM EET 
//


package com.aionemu.packetsamurai.utils.collector.data.npcMoves;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aionemu.packetsamurai.utils.collector.data.npcMoves package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NpcMoves_QNAME = new QName("", "npcMoves");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aionemu.packetsamurai.utils.collector.data.npcMoves
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NpcMoveList }
     * 
     */
    public NpcMoveList createNpcMoveList() {
        return new NpcMoveList();
    }

    /**
     * Create an instance of {@link NpcMove }
     * 
     */
    public NpcMove createNpcMove() {
        return new NpcMove();
    }

    /**
     * Create an instance of {@link Npc }
     * 
     */
    public Npc createNpc() {
        return new Npc();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NpcMoveList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "npcMoves")
    public JAXBElement<NpcMoveList> createNpcMoves(NpcMoveList value) {
        return new JAXBElement<NpcMoveList>(_NpcMoves_QNAME, NpcMoveList.class, null, value);
    }

}
